[project]
name = "rubber-duck"
version = "0.0.1"
description = "Workflow based API to run jobs"
authors = [
  { name = "Jochen Werner", email = "jochen.werner@skaylink.com" },
  { name = "Stefan HeitmÃ¼ller", email = "stefan.heitmueller@skaylink.com" },
]
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
  "pydantic==2.11.4",
  "pydantic-settings==2.9.1",
  "typer==0.15.4",
  "rich==14.0.0",
  "openapi-python-generator==1.2.0",
  "openapi-python-client>=0.25.3",
]

[dependency-groups]
dev = [
  "faker==37.1.0",
  "pytest==8.3.5",
  "pytest-env==1.1.5",
  "pytest-cov==6.1.1",
]

[tool.uv]
default-groups = ["dev"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.pytest_env]
ENDPOINT = "http://dummy-host"
SECRET = "dummy-cmapi-secret"

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
addopts = """-vv"""

[tool.coverage.run]
omit = ["tests/*"]
