---
name: tests
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    env:
      API_BASE_URL: https://xd5gelkkdns3v5yx4x7ullor540qmcbg.lambda-url.eu-central-1.on.aws
      API_ACCESS_TOKEN: this-is-my-secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup mise runtime manager
        uses: jdx/mise-action@v2
        with:
          install: false
          cache: false
          experimental: true
      - name: Install mise
        run: mise install
      - name: Run tests
        run: mise test --cov-fail-under=95
      - name: Create coverage report
        run: echo "<pre>`mise coverage`<pre>" >> $GITHUB_STEP_SUMMARY
